version: "3.9"

services:
  logger:
    build: .
    container_name: iano_whatsapp
    ports:
      - "10000:10000"
    environment:
      - PORT=10000
      - MONGODB_URI=${MONGODB_URI}
      - MONGO_DB=${MONGO_DB}
      - MONGO_COL=${MONGO_COL}
      - MSG_TTL_DAYS=${MSG_TTL_DAYS}
      - WWEBJS_CLIENT_ID=${WWEBJS_CLIENT_ID}
      - WWEBJS_STORE=/app/data/wwebjs
      - MEDIA_DIR=/app/data/media
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_CHAT_MODEL=${OPENAI_CHAT_MODEL}
      - TRANSCRIBE_MODEL=${TRANSCRIBE_MODEL}
      - BOT_NAME=${BOT_NAME}
      - CATALOGO_BASE_URL=${CATALOGO_BASE_URL}
      - DASH_TOKEN=${DASH_TOKEN}
      - HUMAN_HOLD_MS=${HUMAN_HOLD_MS}
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - PUPPETEER_SKIP_DOWNLOAD=true
    volumes:
      - ./data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: iano_whatsapp-frontend
    ports:
      - "9000:9000"
    # Se quiser, pode setar vars aqui também
    environment:
      - NODE_ENV=development
